Enable TLS (#4)
* Getting started on TLS

* Bit more on TLS

* Clean up TLS tests

* reformat actions consistently

* remove reformat action

* test integration test

* Working on itest

* Some itest fixes

* Debugging itest fixes

* Debugging itest fixes

* Debugging itest fixes quoting

* Fix up itest code

* dev container fixes and add insecure server etst class

* Add tls notes

* Cleanup

diff --git a/.github/actions/integration-tests/action.yml b/.github/actions/integration-tests/action.yml
--- a/.github/actions/integration-tests/action.yml
+++ b/.github/actions/integration-tests/action.yml
@@ -15,61 +15,80 @@ inputs:
   gradle-version:
     description: 'Version of Gradle to setup'
     required: false
-    default: 'current'    
+    default: 'current'
+  hostname:
+    description: 'Hostanme to use in integration tests'
+    required: false
+    default: 'integration.restapi.edoatley.com'
+  key-store:
+    description: 'Path to keystore file (relative to docker context)'
+    required: false
+    default: 'src/itest/resources/itest-keystore.jks'
+  key-store-password:
+    secret: true
+    description: 'Password for keystore'
+    required: false
+    default: 'itest'
 
 runs:
   using: 'composite'
   steps:
-      -
-        name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      -
-        name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      -
-        name: Docker Build
-        uses: docker/build-push-action@v5
-        with:
-          context: '${{ inputs.context }}'
-          push: false
-          load: true
-          tags: '${{ inputs.image }}'
-      - 
-        name: Find Free Port
-        id: port
-        run: |
-          BASE_PORT=1234
-          INCREMENT=1
-          port=$BASE_PORT
+  - name: Set up QEMU
+    uses: docker/setup-qemu-action@v3
 
-          while [ -n "$(ss -tan4H "sport = $port")" ]; do
-            port=$((port+INCREMENT))
-          done
-          echo "free_port=$port"
-          echo "free_port=$port" >> $GITHUB_OUTPUT
-        shell: bash
-      - 
-        name: Run Docker Image
-        run: |
-          docker run -d -p ${{ steps.port.outputs.free_port }}:8080 --name restapi ${{ inputs.image }}
-        shell: bash
-      - 
-        name: Run integration test  
-        env:
-          SERVICE_URL: http://localhost:${{ steps.port.outputs.free_port }}
-        working-directory: ${{ inputs.context }}  
-        run: |
-          gradle integrationTest
-        shell: bash
-      - 
-        name: Stop Running Docker Image
-        run: |
-          docker stop restapi
-        shell: bash
-      - 
-        name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: '**/build/test-results/itest/TEST-*.xml'
-  
+  - name: Set up Docker Buildx
+    uses: docker/setup-buildx-action@v3
+
+  - name: Docker Build
+    uses: docker/build-push-action@v5
+    with:
+      context: '${{ inputs.context }}'
+      push: false
+      load: true
+      tags: '${{ inputs.image }}'
+
+  - name: Find Free Port
+    id: port
+    run: |
+      BASE_PORT=1234
+      INCREMENT=1
+      port=$BASE_PORT
+
+      while [ -n "$(ss -tan4H "sport = $port")" ]; do
+        port=$((port+INCREMENT))
+      done
+      echo "free_port=$port"
+      echo "free_port=$port" >> $GITHUB_OUTPUT
+    shell: bash
+
+  - name: Run App as a docker image
+    working-directory: ${{ inputs.context }}
+    run: |
+      docker run -d \
+        -p ${{ steps.port.outputs.free_port }}:8443 \
+        --mount type=bind,source=$(pwd)/${{inputs.key-store}},target=/home/app/tls/keystore.jks,readonly \
+        --env SERVER_KEYSTORE_PASSWORD=${{inputs.key-store-password}} \
+        --name restapi ${{ inputs.image }} 
+    shell: bash
+
+  - name: Run integration test
+    working-directory: ${{ inputs.context }}
+    env:
+      SERVER_PORT: ${{ steps.port.outputs.free_port }}
+      SERVER_KEYSTORE: ${{inputs.key-store}}
+      SERVER_KEYSTORE_PASSWORD: ${{inputs.key-store-password}}
+      SERVER_HOSTNAME: ${{inputs.hostname}}
+    run: |
+      gradle integrationTest
+    shell: bash
+
+  - name: Stop Running Docker Image
+    run: |
+      docker stop restapi
+    shell: bash
+
+  - name: Publish Test Report
+    uses: mikepenz/action-junit-report@v4
+    if: success() || failure() # always run even if the previous step fails
+    with:
+      report_paths: '**/build/test-results/itest/TEST-*.xml'
diff --git a/.github/actions/java-ci-build/action.yml b/.github/actions/java-ci-build/action.yml
--- a/.github/actions/java-ci-build/action.yml
+++ b/.github/actions/java-ci-build/action.yml
@@ -21,7 +21,7 @@ inputs:
   gradle-test-args:
     description: 'Arguments to pass to the gradle test command'
     required: false
-    default: 'test -x integrationTest'    
+    default: 'test -x integrationTest'
   cache-encryption-key:
     description: 'The encryption key to use for caching'
     required: false
@@ -29,38 +29,30 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    - name: Set up JDK
-      uses: actions/setup-java@v4
-      with:
-        distribution: 'adopt'
-        java-version: '${{ inputs.java-version }}'
+  - name: Set up JDK
+    uses: actions/setup-java@v4
+    with:
+      distribution: 'adopt'
+      java-version: '${{ inputs.java-version }}'
 
-    - name: Setup Gradle
-      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
-      with:
-        gradle-version: '${{ inputs.gradle-version }}'
-        cache-encryption-key: ${{ inputs.cache-encryption-key }} 
+  - name: Setup Gradle
+    uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
+    with:
+      gradle-version: '${{ inputs.gradle-version }}'
+      cache-encryption-key: ${{ inputs.cache-encryption-key }}
 
-    - name: Gradle clean and build
-      run: gradle ${{ inputs.gradle-build-args }}
-      shell: bash
-      working-directory: '${{ inputs.working-directory }}'
+  - name: Gradle clean and build
+    run: gradle ${{ inputs.gradle-build-args }}
+    shell: bash
+    working-directory: '${{ inputs.working-directory }}'
 
-    - name: Gradle Unit Test
-      run: gradle ${{ inputs.gradle-test-args }}
-      shell: bash
-      working-directory: '${{ inputs.working-directory }}'
-      
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v4
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: '**/build/test-results/test/TEST-*.xml'
+  - name: Gradle Unit Test
+    run: gradle ${{ inputs.gradle-test-args }}
+    shell: bash
+    working-directory: '${{ inputs.working-directory }}'
 
-    - name: Temporarily save Jar file
-      uses: actions/upload-artifact@v4
-      with:
-        name: restapi-all.jar
-        path: ${{inputs.working-directory}}/build/libs/restapi-all.jar
-        retention-days: 1
-        overwrite: true
+  - name: Publish Test Report
+    uses: mikepenz/action-junit-report@v4
+    if: success() || failure() # always run even if the previous step fails
+    with:
+      report_paths: '**/build/test-results/test/TEST-*.xml'
