Dockerise app and publish to ghcr.io (#6)

diff --git a/.github/actions/integration-tests/action.yml b/.github/actions/integration-tests/action.yml
--- a/.github/actions/integration-tests/action.yml
+++ b/.github/actions/integration-tests/action.yml
@@ -5,9 +5,14 @@ inputs:
   image:
     description: 'What to tag image with'
     required: true
+  registry:
+    description: 'Container registry to push the image to'
+    required: true
+    default: 'ghcr.io'
   context:
     description: 'Docker file / app location'
     required: true
+    default: 'app'
   java-version:
     description: 'Version of JDK to setup'
     required: true
@@ -16,6 +21,9 @@ inputs:
     description: 'Version of Gradle to setup'
     required: false
     default: 'current'
+  cache-encryption-key:
+    description: 'The encryption key to use for gradle caching'
+    required: false
   hostname:
     description: 'Hostanme to use in integration tests'
     required: false
@@ -33,19 +41,17 @@ inputs:
 runs:
   using: 'composite'
   steps:
-  - name: Set up QEMU
-    uses: docker/setup-qemu-action@v3
-
-  - name: Set up Docker Buildx
-    uses: docker/setup-buildx-action@v3
-
-  - name: Docker Build
-    uses: docker/build-push-action@v5
+  - name: Set up JDK
+    uses: actions/setup-java@v4
     with:
-      context: '${{ inputs.context }}'
-      push: false
-      load: true
-      tags: '${{ inputs.image }}'
+      distribution: 'adopt'
+      java-version: '${{ inputs.java-version }}'
+
+  - name: Setup Gradle
+    uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
+    with:
+      gradle-version: '${{ inputs.gradle-version }}'
+      cache-encryption-key: ${{ inputs.cache-encryption-key }}
 
   - name: Find Free Port
     id: port
@@ -61,9 +67,62 @@ runs:
       echo "free_port=$port" >> $GITHUB_OUTPUT
     shell: bash
 
-  - name: Run App as a docker image
+  - name: Log in to the Container registry
+    uses: docker/login-action@v3
+    with:
+      registry: ${{ inputs.registry }}
+      username: ${{ github.actor }}
+      password: ${{ github.token }}
+
+  - name: Build image name
+    id: extract_image
+    shell: bash
+    run: |
+      branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
+      imagename="${{ inputs.registry }}/${{ inputs.image }}:$branch"
+      echo "name=$imagename"
+      echo "name=$imagename" >> $GITHUB_OUTPUT
+
+  - name: Pull the image
+    run: docker pull ${{ steps.extract_image.outputs.name }}
+    shell: bash
+
+  - name: Run App as a docker image and capture startup logs
     working-directory: ${{ inputs.context }}
-    run: "docker run -d \\\n  -p ${{ steps.port.outputs.free_port }}:8443 \\\n  --mount type=bind,source=$(pwd)/${{inputs.key-store}},target=/home/app/tls/keystore.jks,readonly \\\n  --env SERVER_KEYSTORE_PASSWORD=${{inputs.key-store-password}} \\\n  --name restapi ${{ inputs.image }} \n"
+    env:
+      # the two places the env var are used must align
+      DOCKER_KEYSTORE_PATH: /keystore.jks
+    run: |
+      containerid=$(docker run -d \
+        -p ${{ steps.port.outputs.free_port }}:8443 \
+        --mount type=bind,source=$(pwd)/${{inputs.key-store}},target=${{env.DOCKER_KEYSTORE_PATH}},readonly \
+        --env SERVER_KEYSTORE=${{env.DOCKER_KEYSTORE_PATH}} \
+        --env SERVER_KEYSTORE_PASSWORD=${{inputs.key-store-password}} \
+        --name restapi ${{ steps.extract_image.outputs.name }})
+      sleep 20
+      docker logs -t $containerid
+
+    shell: bash
+
+  - name: cURL the endpoint as a sense check
+    run: |
+      success_count=0
+      for i in {1..5}; do
+        curl -vvv -k \
+            -H "Host: ${{ inputs.hostname }}" \
+            -H "Content-Type: application/json" \
+            -d '{"username":"user","password":"password"}' \
+            "https://localhost:${{ steps.port.outputs.free_port }}/api/authentication" 
+        if [ $? -eq 0 ]; then
+          success_count=$((success_count+1))
+        fi
+        sleep 5
+      done
+      if [ $success_count -eq 0 ]; then
+        echo "Failed to connect to the server"
+        docker logs --tail 200 restapi
+        exit 1
+      fi
     shell: bash
 
   - name: Run integration test
@@ -77,7 +136,7 @@ runs:
       gradle integrationTest
     shell: bash
 
-  - name: Print the logs
+  - name: Print the logs from integration tests
     run: docker logs --tail 50 restapi
     shell: bash
     if: always()
