clean up pipeline syntax

diff --git a/.github/actions/integration-tests/action.yml b/.github/actions/integration-tests/action.yml
--- a/.github/actions/integration-tests/action.yml
+++ b/.github/actions/integration-tests/action.yml
@@ -41,6 +41,8 @@ inputs:
 runs:
   using: 'composite'
   steps:
+  - uses: actions/checkout@v4
+
   - name: Set up JDK
     uses: actions/setup-java@v4
     with:
@@ -105,24 +107,7 @@ runs:
     shell: bash
 
   - name: cURL the endpoint as a sense check
-    run: |
-      success_count=0
-      for i in {1..5}; do
-        curl -vvv -k \
-            -H "Host: ${{ inputs.hostname }}" \
-            -H "Content-Type: application/json" \
-            -d '{"username":"user","password":"password"}' \
-            "https://localhost:${{ steps.port.outputs.free_port }}/api/authentication" 
-        if [ $? -eq 0 ]; then
-          success_count=$((success_count+1))
-        fi
-        sleep 5
-      done
-      if [ $success_count -eq 0 ]; then
-        echo "Failed to connect to the server"
-        docker logs --tail 200 restapi
-        exit 1
-      fi
+    run: "success_count=0\nfor i in {1..5}; do\n  curl -vvv -k \\\n      -H \"Host: ${{ inputs.hostname }}\" \\\n      -H \"Content-Type: application/json\" \\\n      -d '{\"username\":\"user\",\"password\":\"password\"}' \\\n      \"https://localhost:${{ steps.port.outputs.free_port }}/api/authentication\" \n  if [ $? -eq 0 ]; then\n    success_count=$((success_count+1))\n  fi\n  sleep 5\ndone\nif [ $success_count -eq 0 ]; then\n  echo \"Failed to connect to the server\"\n  docker logs --tail 200 restapi\n  exit 1\nfi\n"
     shell: bash
 
   - name: Run integration test
